# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('primaryNumber', models.IntegerField()),
                ('primaryPositionCode', models.CharField(choices=[(b'R', b'Right Wing'), (b'C', b'Center'), (b'L', b'Left Wing'), (b'D', b'Defenseman'), (b'G', b'Goalie')], max_length=1)),
                ('birthDate', models.DateField()),
                ('birthCity', models.CharField(max_length=100)),
                ('birthStateProvince', models.CharField(max_length=100)),
                ('birthCountry', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('rookie', models.BooleanField(default=False)),
                ('shootsCatches', models.CharField(max_length=1)),
                ('currentTeam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
        ),
    ]
