# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rosterStatus',
            field=models.CharField(choices=[(b'Y', b'Yes'), (b'N', b'No'), (b'I', b'IR')], default='N', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='primaryNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
