# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbyplay',
            name='playType',
            field=models.CharField(choices=[(b'UNKNOWN', b'Unknown'), (b'FACEOFF', b'Faceoff'), (b'HIT', b'Hit'), (b'GIVEAWAY', b'Giveaway'), (b'GOAL', b'Goal'), (b'SHOT', b'Shot'), (b'MISSED_SHOT', b'Missed Shot'), (b'PENALTY', b'Penalty'), (b'STOP', b'Stoppage'), (b'SUBSTITUTION', b'Substitution'), (b'FIGHT', b'Fight'), (b'TAKEAWAY', b'Takeaway'), (b'BLOCKED_SHOT', b'Blocked Shot'), (b'PERIOD_START', b'Period Start'), (b'PERIOD_END', b'Period End'), (b'GAME_END', b'Game End'), (b'GAME_SCHEDULED', b'Game Scheduled'), (b'PERIOD_READY', b'Period Ready'), (b'PERIOD_OFFICIAL', b'Period Official'), (b'SHOOTOUT_COMPLETE', b'Shootout Complete'), (b'EARLY_INT_START', b'Early Intermission Start'), (b'EARLY_INT_END', b'Early Intermission End'), (b'GAME_OFFICIAL', b'Game Official'), (b'CHALLENGE', b'Official Challenge'), (b'EMERGENCY_GOALTENDER', b'Emergency Goaltender')], max_length=15),
        ),
        migrations.DeleteModel(
            name='PlayType',
        ),
    ]
