# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0002_auto_20160206_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamescratch',
            options={'verbose_name': 'Game Scratch', 'verbose_name_plural': 'Game Scratches'},
        ),
        migrations.AlterModelOptions(
            name='playbyplay',
            options={'verbose_name': 'Play By Play'},
        ),
        migrations.AlterModelOptions(
            name='playergamestats',
            options={'verbose_name': 'Player Game Stats', 'verbose_name_plural': 'Players Game Stats'},
        ),
        migrations.AlterModelOptions(
            name='playeronice',
            options={'verbose_name': 'Player On Ice', 'verbose_name_plural': 'Players On Ice'},
        ),
    ]
