# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0003_auto_20160206_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='link',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='awayScore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='awayShots',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='homeScore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='homeShots',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
