# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0004_auto_20160206_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbyplay',
            name='dateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playbyplay',
            name='gamePk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playbyplay.Game'),
        ),
        migrations.AlterField(
            model_name='playbyplay',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playbyplay',
            name='timeStamp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
