# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0005_auto_20160207_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbyplay',
            name='playType2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
