# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0006_playbyplay_playtype2'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbyplay',
            name='playType3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
