# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0007_playbyplay_playtype3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playbyplay',
            old_name='playType2',
            new_name='playDescription',
        ),
        migrations.RemoveField(
            model_name='playbyplay',
            name='playType3',
        ),
        migrations.RemoveField(
            model_name='playeronice',
            name='timeOnIce',
        ),
        migrations.AddField(
            model_name='playbyplay',
            name='penaltyMinutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playbyplay',
            name='penaltySeverity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='playbyplay',
            name='shotType',
            field=models.CharField(choices=[(b'WRIST', b'Wrist'), (b'SNAP', b'Snapshot'), (b'SLAP', b'Slapshot'), (b'BACK', b'Backhand'), (b'TIP', b'Tip-In'), (b'WRAP', b'Wrap'), (b'DEFLECT', b'Deflected'), (b'UNSPECIFIED', b'Unspecified')], default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playbyplay',
            name='timeOnIce',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playbyplay',
            name='xcoord',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playbyplay',
            name='ycoord',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playbyplay',
            name='playType',
            field=models.CharField(choices=[(b'UNKNOWN', b'Unknown'), (b'FACEOFF', b'Faceoff'), (b'HIT', b'Hit'), (b'GIVEAWAY', b'Giveaway'), (b'GOAL', b'Goal'), (b'SHOT', b'Shot'), (b'MISSED_SHOT', b'Missed Shot'), (b'PENALTY', b'Penalty'), (b'PENALTY_END', b'Penalty Ended'), (b'STOP', b'Stoppage'), (b'SUBSTITUTION', b'Substitution'), (b'FIGHT', b'Fight'), (b'TAKEAWAY', b'Takeaway'), (b'BLOCKED_SHOT', b'Blocked Shot'), (b'PERIOD_START', b'Period Start'), (b'PERIOD_END', b'Period End'), (b'GAME_END', b'Game End'), (b'GAME_SCHEDULED', b'Game Scheduled'), (b'PERIOD_READY', b'Period Ready'), (b'PERIOD_OFFICIAL', b'Period Official'), (b'SHOOTOUT_COMPLETE', b'Shootout Complete'), (b'EARLY_INT_START', b'Early Intermission Start'), (b'EARLY_INT_END', b'Early Intermission End'), (b'GAME_OFFICIAL', b'Game Official'), (b'CHALLENGE', b'Official Challenge'), (b'EMERGENCY_GOALTENDER', b'Emergency Goaltender')], max_length=15),
        ),
    ]
