# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0008_auto_20160207_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbyplay',
            name='xcoord',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='playbyplay',
            name='ycoord',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
