# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0010_auto_20160207_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playbyplay',
            name='timeOnIce',
        ),
    ]
