# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0011_remove_playbyplay_timeonice'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbyplay',
            name='timeOnIce',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
