# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0012_playbyplay_timeonice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbyplay',
            name='shotType',
            field=models.CharField(choices=[(b'WRIST', b'Wrist'), (b'SNAP', b'Snapshot'), (b'SLAP', b'Slapshot'), (b'BACK', b'Backhand'), (b'TIP', b'Tip-In'), (b'WRAP', b'Wrap'), (b'DEFLECT', b'Deflected'), (b'UNSPECIFIED', b'Unspecified')], max_length=12),
        ),
    ]
