# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0014_auto_20160207_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameState',
            field=models.CharField(choices=[(b'1', b'Preview (Scheduled)'), (b'2', b'Preview (Pre-Game)'), (b'3', b'Live (In Progress)'), (b'4', b'Live (In Progress - Critical)'), (b'5', b'Final (Game Over)'), (b'6', b'Final (Final)'), (b'7', b'Final (Final)'), (b'8', b'Preview (Scheduled (Time TBD))'), (b'9', b'Preview (Postponed)')], default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playeronice',
            name='player_type',
            field=models.IntegerField(blank=True, choices=[(0, b'Unknown'), (1, b'Winner'), (2, b'Loser'), (3, b'Hitter'), (4, b'Hittee'), (5, b'Scorer'), (6, b'Assist'), (7, b'Shooter'), (8, b'Goalie'), (9, b'Blocker'), (10, b'PenaltyOn'), (11, b'DrewBy'), (12, b'ServedBy'), (13, b'PlayerID'), (14, b'Fighter'), (15, b'OnIce'), (16, b'Assist 2')], null=True),
        ),
    ]
