# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0016_remove_game_gamestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameState',
            field=models.CharField(choices=[(b'1', b'Preview (Scheduled)'), (b'2', b'Preview (Pre-Game)'), (b'3', b'Live (In Progress)'), (b'4', b'Live (In Progress - Critical)'), (b'5', b'Final (Game Over)'), (b'6', b'Final (Final)'), (b'7', b'Final (Final)'), (b'8', b'Preview (Scheduled (Time TBD))'), (b'9', b'Preview (Postponed)')], default=None, max_length=1),
            preserve_default=False,
        ),
    ]
