# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0017_game_gamestate'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField()),
                ('startTime', models.TimeField(blank=True, null=True)),
                ('endTime', models.TimeField(blank=True, null=True)),
                ('homeScore', models.IntegerField(blank=True, null=True)),
                ('awayScore', models.IntegerField(blank=True, null=True)),
                ('homeShots', models.IntegerField(blank=True, null=True)),
                ('awayShots', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='awayBlocked',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='awayPIM',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='awayPPGoals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='awayPPOpportunities',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='homeBlocked',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='homePIM',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='homePPGoals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='homePPOpportunities',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameperiod',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playbyplay.Game'),
        ),
    ]
