# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20160206_2134'),
        ('playbyplay', '0019_auto_20160207_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='awayGiveaways',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='awayHits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='awayTakeaways',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='firstStar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstStar', to='player.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='homeGiveaways',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='homeHits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='homeTakeaways',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='secondStar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondStar', to='player.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='thirdStar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thirdStar', to='player.Player'),
        ),
    ]
