# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0020_auto_20160207_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbyplay',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
