# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0021_auto_20160207_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbyplay',
            name='eventId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playbyplay',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
