# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0022_auto_20160207_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playbyplay',
            name='gameState',
        ),
        migrations.RemoveField(
            model_name='playbyplay',
            name='link',
        ),
        migrations.RemoveField(
            model_name='playbyplay',
            name='timeStamp',
        ),
        migrations.AddField(
            model_name='playbyplay',
            name='penaltyType',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='playbyplay',
            name='strength',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='playbyplay',
            name='shotType',
            field=models.CharField(blank=True, choices=[(b'WRIST', b'Wrist'), (b'SNAP', b'Snapshot'), (b'SLAP', b'Slapshot'), (b'BACK', b'Backhand'), (b'TIP', b'Tip-In'), (b'WRAP', b'Wrap'), (b'DEFLECT', b'Deflected'), (b'UNSPECIFIED', b'Unspecified')], max_length=12, null=True),
        ),
    ]
