# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0024_playergamestats_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbyplay',
            name='penaltySeverity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playbyplay',
            name='playDescription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
