# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0025_auto_20160207_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbyplay',
            name='penaltyType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
