# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0027_auto_20160207_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playergamestats',
            old_name='playerPlayAssists',
            new_name='powerPlayAssists',
        ),
    ]
