# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0030_auto_20160207_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='awayMissed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='homeMissed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
