# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20160206_2342'),
        ('playbyplay', '0031_auto_20160208_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbyplay',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
    ]
