# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20160206_2342'),
        ('player', '0003_auto_20160206_2134'),
        ('playbyplay', '0032_playbyplay_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalieGameStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField()),
                ('timeOnIce', models.TimeField()),
                ('assists', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('pim', models.IntegerField()),
                ('shots', models.IntegerField()),
                ('saves', models.IntegerField()),
                ('powerPlaySaves', models.IntegerField()),
                ('shortHandedSaves', models.IntegerField()),
                ('evenSaves', models.IntegerField()),
                ('shortHandedShotsAgainst', models.IntegerField()),
                ('evenShotsAgainst', models.IntegerField()),
                ('powerPlayShotsAgainst', models.IntegerField()),
                ('decision', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameState',
            field=models.CharField(choices=[(b'1', b'Preview (Scheduled)'), (b'2', b'Preview (Pre-Game)'), (b'3', b'Live (In Progress)'), (b'4', b'Live (In Progress - Critical)'), (b'5', b'Final (Game Over)'), (b'6', b'Final'), (b'7', b'Final'), (b'8', b'Preview (Scheduled (Time TBD))'), (b'9', b'Preview (Postponed)')], max_length=1),
        ),
        migrations.AddField(
            model_name='goaliegamestats',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playbyplay.Game'),
        ),
        migrations.AddField(
            model_name='goaliegamestats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player'),
        ),
        migrations.AddField(
            model_name='goaliegamestats',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
    ]
