# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20160206_2134'),
        ('playbyplay', '0035_auto_20160211_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayByPlayPlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a1', to='player.Player')),
                ('a2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a2', to='player.Player')),
                ('a3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a3', to='player.Player')),
                ('a4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a4', to='player.Player')),
                ('a5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a5', to='player.Player')),
                ('a6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a6', to='player.Player')),
                ('h1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='h1', to='player.Player')),
                ('h2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='h2', to='player.Player')),
                ('h3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='h3', to='player.Player')),
                ('h4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='h4', to='player.Player')),
                ('h5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='h5', to='player.Player')),
                ('h6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='h6', to='player.Player')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playbyplay.PlayByPlay')),
            ],
        ),
    ]
