# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20160206_2134'),
        ('playbyplay', '0036_playbyplayplayers'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbyplayplayers',
            name='a7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a7', to='player.Player'),
        ),
        migrations.AddField(
            model_name='playbyplayplayers',
            name='h7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='h7', to='player.Player'),
        ),
    ]
