# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0037_auto_20160215_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbyplay',
            name='eventIdx',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
