# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20160206_2134'),
        ('playbyplay', '0039_auto_20160217_0934'),
    ]

    operations = [
    ]
