# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0040_auto_20160217_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playbyplayplayers',
            name='a1',
        ),
        migrations.RemoveField(
            model_name='playbyplayplayers',
            name='a2',
        ),
        migrations.RemoveField(
            model_name='playbyplayplayers',
            name='a3',
        ),
        migrations.RemoveField(
            model_name='playbyplayplayers',
            name='a4',
        ),
        migrations.RemoveField(
            model_name='playbyplayplayers',
            name='a5',
        ),
        migrations.RemoveField(
            model_name='playbyplayplayers',
            name='a6',
        ),
        migrations.RemoveField(
            model_name='playbyplayplayers',
            name='a7',
        ),
        migrations.RemoveField(
            model_name='playbyplayplayers',
            name='h1',
        ),
        migrations.RemoveField(
            model_name='playbyplayplayers',
            name='h2',
        ),
        migrations.RemoveField(
            model_name='playbyplayplayers',
            name='h3',
        ),
        migrations.RemoveField(
            model_name='playbyplayplayers',
            name='h4',
        ),
        migrations.RemoveField(
            model_name='playbyplayplayers',
            name='h5',
        ),
        migrations.RemoveField(
            model_name='playbyplayplayers',
            name='h6',
        ),
        migrations.RemoveField(
            model_name='playbyplayplayers',
            name='h7',
        ),
        migrations.RemoveField(
            model_name='playbyplayplayers',
            name='play',
        ),
        migrations.DeleteModel(
            name='PlayByPlayPlayers',
        ),
    ]
