# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='venue',
            unique_together=set([('name', 'city')]),
        ),
    ]
