# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20160206_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('goalsAgainst', models.IntegerField()),
                ('goalsScored', models.IntegerField()),
                ('points', models.IntegerField()),
                ('gamesPlayed', models.IntegerField()),
                ('streakCode', models.CharField(blank=True, max_length=3, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
        ),
    ]
