# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_seasonstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonstats',
            name='losses',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='ot',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='wins',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
