# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 14:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20160209_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonstats',
            name='date',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 2, 9, 14, 39, 54, 185340, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='seasonstats',
            unique_together=set([('date', 'team')]),
        ),
    ]
