# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20160209_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonstats',
            name='goalsAgainst',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasonstats',
            name='goalsScored',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
