# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_auto_20160210_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonstats',
            name='date',
            field=models.DateField(),
        ),
    ]
